"""empty message

Revision ID: 8bf6f62d9f60
Revises: 0ac23fedbee1
Create Date: 2016-07-05 14:49:31.932034

"""

# revision identifiers, used by Alembic.
revision = '8bf6f62d9f60'
down_revision = '0ac23fedbee1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'session_token')
    ### end Alembic commands ###
